---
- name: Configuring Logging
  template:
    src: logback.xml.j2
    dest: "{{ kafka_lag_exporter_config_dir }}/{{ kafka_lag_exporter_logging_config_filename }}"
    mode: 0644
    owner: "{{ kafka_lag_exporter_user }}"
    group: "{{ kafka_lag_exporter_group }}"
  notify: restart lag-exporter
- name: Configuring Kafka Lag Exporter
  template:
    src: application.conf.j2
    dest: "{{ kafka_lag_exporter_config_dir }}/{{ kafka_lag_exporter_config_filename }}"
    mode: 0644
    owner: "{{ kafka_lag_exporter_user }}"
    group: "{{ kafka_lag_exporter_group }}"
  notify: restart lag-exporter
- name: Configuring Kafka Lag Exporter System.d
  template:
    src: systemd.conf.j2
    dest: "{{ kafka_lag_exporter_service_systemd_file }}"
    mode: 0644
    owner: "{{ kafka_lag_exporter_user }}"
    group: "{{ kafka_lag_exporter_group }}"
  notify: restart lag-exporter
- name: Configuring Kafka Lag Exporter System.d Override
  template:
    src: override.conf.j2
    dest: "{{ kafka_lag_exporter_service_systemd_override }}"
    mode: 0644
    owner: "{{ kafka_lag_exporter_user }}"
    group: "{{ kafka_lag_exporter_group }}"
  notify: restart lag-exporter